[package]
name = "simulation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
glam.workspace = true
physics.workspace = true
voxel_world.workspace = true
protocol.workspace = true
networking.workspace = true
parking_lot = "0.12"
gpu_physics = { path = "../gpu_physics" }
