[package]
name = "voxel-client"
version.workspace = true
edition.workspace = true

[features]
tracy = ["bevy/trace", "bevy/trace_tracy"]

[dependencies]
bevy.workspace = true
image = "0.25"
serde_json.workspace = true
voxel_world.workspace = true
voxel_render.workspace = true
physics.workspace = true
controller.workspace = true
protocol.workspace = true
networking.workspace = true
gameplay.workspace = true
