[package]
name = "game_packages"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
voxel_world.workspace = true
protocol.workspace = true
controller.workspace = true
gameplay.workspace = true
parking_lot = "0.12"
steel = { package = "steel-core", version = "=0.8.2", default-features = false, features = ["std", "sandbox", "interrupt"] }

[dev-dependencies]
glam.workspace = true
